### ISSUE TITLE
Are Form Field Values Compared?

### ISSUE THREAD

**Issue by rpigneri-vol** [marcdacz/compare-pdf#12]
Dear compare-pdf team,

We are looking for a PDF comparator, and compare-pdf seems really nice.  However, I'm having trouble getting it to consistently evaluate PDF files with fillable fields.  Does compare-pdf compare form values as well, or just the static contents of the PDF?

Thank you!

**Comment by marcdacz** [comment]
hi mate, compare-pdf converts each page into an image and then compare it to the baseline / reference. that means we do not compare by value but instead by image (pixel comparison)
