### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by manuman94** [marcdacz/compare-pdf#14]
I would be great to have Typescript type definitions as most of the frameworks nowadays use Typescript.

Thank you, greetings.

**Comment by marcdacz** [comment]
I'll look into this. However, if you guys have a PR to support this, I'll be happy to merge.

**Comment by marcdacz** [comment]
Thanks for your patience. A [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61050) has been raised in DefinitelyTyped repo.
