### ISSUE TITLE
Error when ran from within Cypress

### ISSUE THREAD

**Issue by tsposato** [marcdacz/compare-pdf#16]
I followed the Cypress example exactly and I run into the following issue.
I'm simply trying to compare 2 PDF's (the same files during the test).
Sample code is exactly the same.
I'm running: 
node v14.16.1
npm 6.14.12

Same error on Windows 10 and on Ubuntu 20.10 whether I use headed or headless modes.

![image](https://user-images.githubusercontent.com/27261670/144180104-9589edfe-5e22-47f6-95cc-af7bae9abb74.png)

**Comment by marcdacz** [comment]
based on the error message you need to have Node v9.2+
can you try upgrading your node version and see how it goes?

**Comment by tsposato** [comment]
> based on the error message you need to have Node v9.2+ can you try upgrading your node version and see how it goes?

I'm using node v14.16.1.

**Comment by humphreyn** [comment]
Hi @tsposato, I am using Node v14 as well but I do not get that error message.

Could you do two things:
Add the following piece of code prior to any "require ..." in your code:

`console.log("versions: ", process.versions);`

Then please forward on output of the console.log and also a full stack trace

**Comment by marcdacz** [comment]
Thanks for raising this issue @tsposato. However, I am closing this issue as we did not receive any more updates since @humphreyn++++ asked his question.
