### ISSUE TITLE
Docs to describe config settings

### ISSUE THREAD

**Issue by robross0606** [marcdacz/compare-pdf#2]
There is no explanation of what things like `quality` `tolerance` and `threshold` mean.  These are not intuitively obvious, so some explanation in the readme would be useful.

**Comment by marcdacz** [comment]
Hi @robross0606, 
Thanks for highlighting this issue.
I will try to update the documentation for this.
I'll close this once its done.

**Comment by marcdacz** [comment]
I've updated the docs with the following:
Settings:
PDF to Image Conversion

density: (from gm) This option specifies the image resolution to store while encoding a raster image or the canvas resolution while rendering (reading) vector formats into an image.
quality: (from gm) Adjusts the jpeg|miff|png|tiff compression level. val ranges from 0 to 100 (best).
cleanPngPaths: This is a boolean flag for cleaning png folders automatically
Image Comparison

tolerance: This is the allowable pixel count that is different between the compared images.
threshold: (from pixelmatch) Matching threshold, ranges from 0 to 1. Smaller values make the comparison more sensitive. 0.1 by default.
