### ISSUE TITLE
Browser-Side Usage

### ISSUE THREAD

**Issue by SquishyMucus** [marcdacz/compare-pdf#21]
Is there any possibility of using this on the browser side?

Looking at the errors generated, most of them are involving the 'path' and 'fs' modules so that would suggest that it's  server-side only. Could you confirm that getting this to work on browser is not possible and I'll know to look for other options.

Thanks

**Comment by marcdacz** [comment]
As you have already pointed out, since it is using fs and path, this is only going to work on server side unfortunately.
