### ISSUE TITLE
No try catch block to catch any await promise rejections in comparePdfByImage

### ISSUE THREAD

**Issue by humphreyn** [marcdacz/compare-pdf#24]
The function comparePdfByImage in ./functions/compareImage.js has no try catch block so any promise rejections by await calls to imageEngine.* are not caught

I would add a try catch block inside the ..new Promise and either reject the error or resolve it with a failed status

```
const comparePdfByImage = async (compareDetails) => {
	return new Promise(async (resolve, reject) => {
		try {
                ..... // original code block
                .....
                .....
                .....

		} catch (error) {
                        // reject or resolve it with failed status
			reject(error);  
			resolve({ status: 'failed',  error: error });
		}
	});
```

**Comment by marcdacz** [comment]
Thanks for raising this. Fixed it in this [commit](https://github.com/marcdacz/compare-pdf/commit/34868d3800b171773f84e0f5ef1e688d8d37e1d6) and will be released in the next one.
