### ISSUE TITLE
Empty diffPngs directories

### ISSUE THREAD

**Issue by ngmiduc** [marcdacz/compare-pdf#25]
Hi,

after running with the config: `cleanPngPaths = true`, it deletes the actual and expected file paths but not the diffs. I will end up with a lot of empty folders.

Is this expected or a bug?
<img width="1002" alt="Screenshot 2022-05-31 at 20 33 33" src="https://user-images.githubusercontent.com/22853830/171259774-6c49e7a7-edb6-44c9-8148-60ad3e373654.png">

It would be nice maybe to have a possibility to name the diffPng folder, so it is easier to find the folder for the failed comparisons.

**Comment by marcdacz** [comment]
Thanks for raising this. I believe this is an expected behaviour as we would like to retain the results post test execution. 
The diff folder is configurable but the diff png file is based on your actual pdf filename. Is it possible for you to change your actual pdf filename to a more static one?
