### ISSUE TITLE
How to addMask only specific test case / file ?

### ISSUE THREAD

**Issue by voravuthbo** [marcdacz/compare-pdf#26]
Hi,

First of all sorry for my english. I've noticed something that if I have 2 test cases in one test file and the first test case got file masked. The file in the second test case will got masked too.

![image](https://user-images.githubusercontent.com/46745977/175206246-6832c57a-4700-41bc-8309-46086240a3bd.png)

Those files are in the same folder.

![image](https://user-images.githubusercontent.com/46745977/175206432-5413afb4-a8d0-47e5-9843-6a3c8c79c2c0.png)

The workaround is to move the unmasked test case (which is second test case) to the first one instead but I think it's not the proper way.

Below is the config file.

```
const comparePdfConfig = {
    paths: {
        actualPdfRootFolder: process.cwd() + "/testFiles/pdf/actual",
        baselinePdfRootFolder: process.cwd() + "/testFiles/pdf/baseline",
        actualPngRootFolder: process.cwd() + "/testFiles/actualPngs",
        baselinePngRootFolder: process.cwd() + "/testFiles/baselinePngs",
        diffPngRootFolder: process.cwd() + "/testFiles/diffPngs"
    },
    settings: {
        density: 150,
        quality: 80,
        tolerance: 0,
        threshold: 0.1,
        cleanPngPaths: false
    }
};

module.exports = { comparePdfConfig };
```

How can I mask the file for specific file or test case?

**Comment by marcdacz** [comment]
Thanks for raising this issue. I was able to investigate and reproduce and I have fixed it in v1.1.7
