### ISSUE TITLE
Failing on comparing two relatively simple PDFs

### ISSUE THREAD

**Issue by robross0606** [marcdacz/compare-pdf#3]
I have two PDF files that the library is failing as if they're different mostly because it is generating images that are quite different than one another.  I have attached the original and comparison PDF, as well as the PNGs generated from the comparison
[snapshot.pdf](https://github.com/marcdacz/compare-pdf/files/4518945/snapshot.pdf)
[new.pdf](https://github.com/marcdacz/compare-pdf/files/4518947/new.pdf)
![snapshot](https://user-images.githubusercontent.com/2965467/80032399-1b4bf380-84b9-11ea-91af-406095f9ef8a.png)
![new](https://user-images.githubusercontent.com/2965467/80032415-2141d480-84b9-11ea-994d-059d2b1e7e71.png)
![diff](https://user-images.githubusercontent.com/2965467/80032435-29017900-84b9-11ea-9e3e-8a0ecf4016c1.png)
As you can see, the baseline snapshot PDF and generated PDF are basically identical.  However, the generated PNG are fairly different and fail the diff with lots of pixel differences.

**Comment by robross0606** [comment]
The results appear to be different depending upon which OS the comparison is run on.  On Windows the results pass.  On Alpine Linux the test fails.  Do you have any tips or guidance on how the settings could be tweaked?  Is there a way to increase the resolution of the PNG files?  They're quite low resolution right now.

**Comment by marcdacz** [comment]
Hi @robross0606,

As you may have observed, there is a different rendering engine between OS.
Thanks for raising #2 as well. I am updating the README for this module to add the settings to tweak the quality of the pdf -> png conversion. For now, here are the settings:

### PDF to Image Conversion

**density**: (from gm) This option specifies the image resolution to store while encoding a raster image or the canvas resolution while rendering (reading) vector formats into an image.
**quality**: (from gm) Adjusts the jpeg|miff|png|tiff compression level. val ranges from 0 to 100 (best).
**cleanPngPaths**: This is a boolean flag for cleaning png folders automatically

### Image Comparison

**tolerance**: This is the allowable pixel count that is different between the compared images.
**threshold**: (from pixelmatch) Matching threshold, ranges from 0 to 1. Smaller values make the comparison more sensitive. 0.1 by default.

**Comment by robross0606** [comment]
Ultimately, I couldn't find a set if values that would allow comparisons between PDF generated on different OS to match.  Even using a consistent embedded web font, the differences were too much to make this even remotely useful.
