### ISSUE TITLE
errors in .d.ts file

### ISSUE THREAD

**Issue by cnpog** [marcdacz/compare-pdf#33]
Found 2 typing problems in the .d.ts file

`export = ComparePdf;` 
should be 
`export default ComparePdf;`

and

`compare(comparisonType?: string): Results;` 
should be 
`compare(comparisonType?: string): Promise<Results>;`

Would be nice if you could add these changes.

**Comment by harshkhare3** [comment]
Here is one more problem

`interface Results {
    status: string;
    message: string;
    details?: Details;
}`
should be 
`interface Results {
    status: string;
    message: string;
    details?: Array<Details>;
}`

Please add these changes @AJ-72

**Comment by trogulja** [comment]
Here is one more problem:

`baselinePdfBuffer`'s as well as other `...Buffer` function's second argument should be mandatory:

- if it's not set, `compare` function will have `compareDetails.actualPdfFilename` set to `undefined` (as well as `compareDetails.baselinePdfFilename`
- which will get consumed in the `comparePdfByImage` function in a call to `path.parse()` (compareImages.js, line 50)...
- this will throw an error: `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

I've opened PR #39 that fixes these issues
