### ISSUE TITLE
Manage Only error with percentage of differrence

### ISSUE THREAD

**Issue by agugut-nexgen** [marcdacz/compare-pdf#4]
Hello
I have some pdf to compare but these pdfs have some changes like date of creation
The plugin that you develop is very useful, but maybe could be possible set a general percentage difference and not use the quantity of pixels
Maybe could be added as new feature
Thanks in advance...

**Comment by marcdacz** [comment]
Hi @agugut, sure I can consider this for options for comparison. I'll try to look into it and get back to you. 
Thanks for using this module.
Stay awesome!

**Comment by marcdacz** [comment]
hi @agugut, 
was wondering if you can use the mask function to cover the dynamic data such as dates.
that way you don't need to increase the the tolerance instead which is way more safer in testing.
